### ISSUE TITLE
about training/test data

### ISSUE THREAD

**Issue by AlexSandro93** [qzhang95/HSID-CNN#3]
Hi, Can you provide the training/test data in matlab format, or suggest which pre-processing have you done to the entire washington DC image ? (I cannot subscript an account on Baidu for downloading the data).

**Comment by WHUQZhang** [comment]
WDC data can be downloaded at https://engineering.purdue.edu/~biehl/MultiSpec/hyperspectral.html. Before the denoising process, the gray values of each HSI band were all normalized to [0, 1] band by band.

**Comment by qzhang95** [comment]
> Hi, Can you provide the training/test data in matlab format, or suggest which pre-processing have you done to the entire washington DC image ? (I cannot subscript an account on Baidu for downloading the data).

WDC data can be downloaded at https://engineering.purdue.edu/~biehl/MultiSpec/hyperspectral.html. Before the denoising process, the gray values of each HSI band were all normalized to [0, 1] band by band.

**Comment by AlexSandro93** [comment]
Yes I've already tried with this image. But I not obtain the same results. You use some toolbox to read the image (I use simply imread)? And for visualization you use imadjust or some other functions?  What I do is:
1) Normalization band by band in range [0,1] of the entire image
2) Split train/test
3) Addition of noise (already present in your test code)

If I not use imadjust to the Washington dc image I obtain this strange effect:

![total_wr](https://user-images.githubusercontent.com/47394005/54533784-43e6ed00-498b-11e9-95e3-5e043ef5dbcc.jpg).
Thank you for your help.

**Comment by qzhang95** [comment]
Something in your band normalization seems inapposite.

**Comment by AlexSandro93** [comment]
How have you normalize the data? I'm simply rescaling in the range [0,1] with the following formula:
  
Xij = (𝑥𝑖𝑗 − bandmin) ⁄ (bandmax−bandmin) ;
where i is the spatial position and j is the band index.

**Comment by qzhang95** [comment]
The normalizing way is right. Maybe your data have abnormal values  and you need removal them.

**Comment by AlexSandro93** [comment]
Can you please upload your full image on google drive for example? you would give me a big help.

**Comment by qzhang95** [comment]
You can downloaded LRMR/LRTV codes and data as the examples.

**Comment by AlexSandro93** [comment]
Yes I have already the indian pines and the Pavia dataset. But to make a comparison I need your Washington dc dataset.
